# Fichier vide pour empêcher Render de détecter Poetry
# Ce projet utilise pip et requirements.txt
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []
