services:
  - type: web
    name: arkalia-quest
    runtime: docker
    plan: free
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true
