services:
  - type: web
    name: arkalia-quest
    runtime: docker
    plan: free
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: GUNICORN_PRELOAD
        value: "true"
      - key: GUNICORN_WORKERS
        value: "2"
    healthCheckPath: /health
    autoDeploy: true
