name: Deploy
'on':
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to production
      run: echo 'Deploying...'
