version: "3.8"

services:
  arkalia-quest:
    build:
      context: ..
      dockerfile: config/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      - ../logs:/app/logs
      - ../data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Base de données SQLite (optionnel pour le développement)
  # sqlite:
  #   image: alpine:latest
  #   volumes:
  #     - ../data:/data
  #   command: sh -c "apk add --no-cache sqlite && sqlite3 /data/arkalia.db 'CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT);'"
